paths:
  planitapp: 'backbone/planit_app'
  backbone: 'application/lib/backbone'
  underscore: 'application/lib/underscore'
  routers: 'backbone/routers'
  views: 'backbone/views'
  models: 'backbone/models'
  collections: 'backbone/collections'
  templates: 'backbone/templates'
  text: 'application/lib/text'
  hbs: 'application/lib/hbs'

shim:
  jquery:
    exports: $
  underscore:
    deps: ['jquery']
    exports: _
  backbone:
    deps: ['underscore', 'jquery']
    exports: Backbone
  bootstrap:
    deps: ['jquery']
    exports: bootstrap
  datetimepicker:
    deps: ['bootstrap']
    exports: $.fn.datetimepicker